### ISSUE TITLE
Export error with png attachment

### ISSUE THREAD

**Issue by aelsenaar** [kevindurston21/YANOM-Note-O-Matic#69]
**Describe the bug**

I get the following unhandled exception when exporting a note with a png file as an attachment:

![image](https://user-images.githubusercontent.com/16883460/148820036-53b29086-f770-43c3-83cd-d70a26fe8963.png)

**To Reproduce**
1. Create a Note with a png as a file attachment
2. Create a nsx export
3. Convert the NSX fiel to MD files

**Expected behavior**
I expect the note to be converted to a MD file with a refenrence to the PNG attachment

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Yanom Version: 1.6.0

**Additional context**
[20220111_000852_4606_ae.zip](https://github.com/kevindurston21/YANOM-Note-O-Matic/files/7842463/20220111_000852_4606_ae.zip)

**Comment by aelsenaar** [comment]
It looks like it also happens with a jpg file as an attachment.

**Comment by kevindurston21** [comment]
Hi Alexander,

Thanks.  I've confirmed it here.  Will look into it.

Cheers,


Kevin

**Comment by kevindurston21** [comment]
Hi,

Found and fixed.

- Code assumed all images would be displayed on the page ,and so treated attached png as a displayed image.  
- Displayed images in the note have data the attached images do not.  
- Now checks for that extra data and use its presence or not to  get the right status of attached image or displayed image.before assuming the attachment is displayed or not.  

I hope to build 1.6.1 files tomorrow evening.

**Comment by aelsenaar** [comment]
Hi Kevin,

Thanks for the fast response and fix. I will test it as soon as it is available.

**Comment by kevindurston21** [comment]
Hi,

Just released 1.6.1.  Let me know if there are nay more issues

Cheers

Kevin

**Comment by aelsenaar** [comment]
Hi,

I did some testing and, it works like a charm.

Thanks for the fix.

Cheers
Alexander
